#
# The 'ClientAliveInterval' setting determines the amount of time (in seconds)
# the sshd server will wait to receive data from the client before sending a
# request for response.
#
# The Azure marketplace does not allow a value greater than 3 minutes. So, when
# running on Azure, we use 3 minutes.
#
ClientAliveCountMax 0
ClientAliveInterval 180
