#!/bin/bash

#
# Enable specific pr_debug() statements in the kernel to aid in debugging
# potential issues. The debug statements can only be enabled on loaded modules,
# so we manually load some modules that aren't loaded by default.
#
modprobe target_core_mod
modprobe iscsi_target_mod
cat <<-EOF >/sys/kernel/debug/dynamic_debug/control
	# iSCSI debug info related to LUN RESETs and iSCSI reconnects.
	file target_core_tmr.c +p
	func iscsit_release_commands_from_conn +p
EOF

echo "pr_debug statements enabled:"
grep '=p' /sys/kernel/debug/dynamic_debug/control

#
# We do not want to fail the service if some of the dynamic debug fails
# to apply
#
exit 0
