#!/bin/bash
#
# Copyright 2019 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

MIGRATE_CONFIG_SCRIPT="/opt/delphix/migration/migrate_config.py"
MIGRATE_CONFIG_LOG="/var/delphix/migration/log"
PG_REINDEX=/var/delphix/server/db/force-reindex

#
# The perform-migration flag file is created by dx_execute prior rebooting
# into Linux.
#
PERFORM_MIGRATION="/var/delphix/migration/perform-migration"

function die() {
	echo "$(basename "$0"): $*" >&2
	exit 1
}

#
# Perform first-boot migration steps.
# This function must be idempotent. If some of the steps fail, we must
# be able to manually fix the problem, then re-run the migration service
# to resume the upgrade.
#
function perform_migration() {
	echo "chown -R /var/delphix/server"
	chown -R root:root /var/delphix/server ||
		die "Failed to chown /var/delphix/server"

	if [[ -d /var/delphix/dmsuite ]]; then
		echo "moving /var/delphix/dmsuite to /var/delphix/masking"
		mv -T /var/delphix/dmsuite /var/delphix/masking ||
			die "Failed to move masking data directory"
	else
		echo "note: /var/delphix/dmsuite doesn't exist"
	fi

	if [[ -d /var/delphix/masking ]]; then
		echo "chown -R /var/delphix/masking"
		chown -R masking:staff /var/delphix/masking ||
			die "Failed to chown masking data directory"
	fi

	if zpool list domain0 >/dev/null 2>&1; then
		echo "note: domain0 is already imported"
	else
		echo "importing domain0"
		#
		# In most cases, use the devices' by-id links to import
		# domain0. This ensures persistent vdev names which can
		# tolerate device reordering. AWS does not provide a by-id
		# link, so we use simple device names (i.e. /dev/xvda). On
		# Azure, however, we use the Azure-specific links, because the
		# by-id links can change when the device is resized.
		#
		BY_ID_LINK="/dev/disk/by-id"
		AZURE_LINK="/dev/disk/azure"
		if [[ -d "$AZURE_LINK" ]]; then
			dir_array=()
			while read -r dir; do
				dir_array+=(-d)
				dir_array+=("$dir")
			done < <(find "$AZURE_LINK" -maxdepth 1 -name "scsi*")
			echo "zpool import -fN ${dir_array[*]} domain0"
			zpool import -fN "${dir_array[@]}" domain0 ||
				die "Failed to import domain0 by azure link"
		elif [[ -d "$BY_ID_LINK" ]]; then
			echo "zpool import -fN -d $BY_ID_LINK domain0"
			zpool import -fN -d $BY_ID_LINK domain0 ||
				die "Failed to import domain0 by-id"
		else
			echo "zpool import -fN domain0"
			zpool import -fN domain0 ||
				die "Failed to import domain0"
		fi
	fi

	#
	# sharenfs is set when a dataset (VDB/dSource) is shared and is
	# cleared when it is stopped or quiesced. At this point in time,
	# this property will only be set for datasets that failed to be
	# quiesced before the upgrade reboot. The sharenfs setting was
	# set on Illumos with options specific to Illumos and targetting
	# an NFS version that may be different on Linux. As such, attempting
	# to migrate it could result in unexpected behaviour, so we clear
	# it instead. We rely on the user to manually restart any VDBs that
	# failed to quiesce.
	#
	echo "clearing sharenfs properties"
	zfs inherit -r sharenfs domain0 ||
		die "failed to clear sharenfs properties"

	echo "mounting ZFS file-systems"
	zfs mount -a || die "Failed to mount zfs file-systems"

	#
	# domain0/mds is owned by delphix:staff on Illumos, and on Linux
	# postgres can't access this dataset anymore. We change the
	# permissions to the Linux defaults.
	#
	echo "chown -R /mds"
	chown -R postgres:postgres /mds ||
		die "Failed chowning /mds"

	#
	# For each domain0 dataset with a default mountpoint,
	# the parents need other-execute for NFSv4 exports.
	#
	echo "Fixing mountpoint permissions for domain0 datasets"
	DATASETS=$(zfs list -H -r -t filesystem -o mountpoint domain0 |
		grep ^/domain0/ | xargs dirname | sort | uniq)

	for DATASET in $DATASETS; do
		if [[ "$DATASET" == "/domain0" ]]; then
			continue
		fi
		PERMS=$(stat "$DATASET" -c %a 2>/dev/null)
		RETURN=$?
		if [[ $RETURN -eq 0 && "$PERMS" == "750" ]]; then
			echo "chmod o+x $DATASET"
			chmod o+x "$DATASET" ||
				die "Failed chmod o+x $DATASET"
		fi
	done

	#
	# Wait on zvol dev links to be ready.
	# This must be done after we import domain0 and before we attempt
	# to start the rtslib-fb-targetctl service, which depends on the
	# current service.
	#
	zvol_wait || die "Failed waiting on zvol dev links."

	#
	# DLPX-63949: Postgres must be re-indexed after migration.
	# See dx_pg_post_start.sh for more info.
	#
	touch "$PG_REINDEX" || die "Failed to create $PG_REINDEX"
	chown postgres "$PG_REINDEX" || die "Failed to chown $PG_REINDEX"

	echo "$(date): Running migrate_config post-upgrade" \
		>>"$MIGRATE_CONFIG_LOG"
	"$MIGRATE_CONFIG_SCRIPT" post-upgrade >>"$MIGRATE_CONFIG_LOG" 2>&1 ||
		die "Failed migrate_config post-upgrade, see" \
			"$MIGRATE_CONFIG_LOG"
	rm "$PERFORM_MIGRATION" || die "Failed to remove $PERFORM_MIGRATION"
}

if [[ -f "$PERFORM_MIGRATION" ]]; then
	echo "File $PERFORM_MIGRATION exists. Performing OS migration ..."
	perform_migration
	echo "OS migration completed"
else
	echo "File $PERFORM_MIGRATION missing. Nothing to do."
fi
