#!/bin/bash -eux
#
# Copyright 2018, 2021 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DEFAULT_UDEV_NET_SETUP_LINK_DIR="/usr/lib/udev/rules.d"
MODIFIED_UDEV_NET_SETUP_LINK_DIR="/etc/lib/udev/rules.d"

case $1 in
configure)
	systemctl disable apt-daily.service
	systemctl disable apt-daily.timer

	systemctl disable apt-daily-upgrade.service
	systemctl disable apt-daily-upgrade.timer

	#
	# We need to make sure that the motd-news.service is disabled. This
	# service reaches out to a public Ubuntu news service over the public
	# Internet to cache dynamic content that is then optionally printed by
	# /etc/update-motd.d/50-motd-news. There are at least three problems
	# with this:
	#
	# 1. We don't want engines in customer environments reaching out to
	#    public services.
	# 2. We don't care about the dynamic content provided by Ubuntu.
	# 3. The service explicitly runs the /etc/update-motd.d/50-motd-news
	#    script and fails if that script isn't executable, and we
	#    turn off all executable bits on files in this directory except
	#    those supplied by Delphix to suppress non-Delphix motd messages.
	#
	# As such, the service needs to be disable, which involves both the
	# service unit along with the timer unit that is tasked with running it
	# every 12 hours.
	#
	systemctl disable motd-news.service
	systemctl disable motd-news.timer

	systemctl enable auditd.service
	systemctl enable delphix.target
	systemctl enable delphix-platform.service
	systemctl enable delphix-rpool-upgrade.service
	systemctl enable systemd-networkd.service
	systemctl enable iscsi-name-init.service

	if ! id -u postgres >/dev/null; then
		# When installing postgres, a postgres user is created unless it
		# already exists. To have a consistent UID accross installations
		# and with systems that were migrated from Illumos, we create a
		# user with the same UID as in Illumos. The Ubuntu postgres
		# package requires that the postgres user is also part of the
		# postgres group. Again, for consistency, we create the postgres
		# group with a pre-determined GID, which the same as the
		# postgres UID. Note that we put this code here instead of the
		# delphix-platform service as we need it to be executed before
		# the postgres package gets installed.
		addgroup postgres --gid 65437
		adduser --home /var/lib/postgresql --no-create-home \
			--shell /bin/bash --ingroup postgres \
			--gecos "PostgreSQL administrator" --uid 65437 \
			--disabled-password postgres
	elif [[ $(id -u postgres) -ne 65437 ]]; then
		echo "ERROR: postgres id $(id -u postgres) != 65437" >&2
		exit 1
	fi

  # We are switching to MAC address based network interface names only in AWS environment
  # from 6.0.10.0 onwards. To handle this change, we leverage the default 80-net-setup-link.rules udev
  # rules file. We make a copy of this file under /etc and then change the naming policy to MAC address
  # based names. Please see DLPX-75209 for more context on this change.
  # Though unlikely, it is still remotely possible that the /usr/lib/udev/rules.d/80-net-setup-link.rules
  # file either gets removed from the base OS distribution or gets replaced with another file to serve
  # the exact/similar purpose. We must detect and inspect such a change and update the renaming logic if
  # needed. Ideally, we should also detect changes in the contents of this file but we doubt there is an
  # obvious way of accomplishing this today.
  if [[ ! -e "$DEFAULT_UDEV_NET_SETUP_LINK_DIR"/80-net-setup-link.rules ]]; then
    echo "$DEFAULT_UDEV_NET_SETUP_LINK_DIR/80-net-setup-link.rules found missing, investigation needed to understand "\
      "if its location has changed or if the file itself has been replaced with another udev rules file" >&2
    exit 1
  fi
  if [[ "$(get-appliance-platform)" == "aws" ]]; then
    # If there are any changes in the specific line of the rules file that we are modifying, we fail early
    # to allow us the opportunity to investigate the changes and update our own changes accordingly.
    grep "^NAME==\"\", ENV{ID_NET_NAME}\!=\"\", NAME=\"\$env{ID_NET_NAME}\""\
      "$DEFAULT_UDEV_NET_SETUP_LINK_DIR"/80-net-setup-link.rules
    if [[ ! -d "$MODIFIED_UDEV_NET_SETUP_LINK_DIR" ]]; then
      mkdir -p "$MODIFIED_UDEV_NET_SETUP_LINK_DIR"
    fi
    cp "$DEFAULT_UDEV_NET_SETUP_LINK_DIR"/80-net-setup-link.rules "$MODIFIED_UDEV_NET_SETUP_LINK_DIR"
    sed -i 's/ID_NET_NAME/ID_NET_NAME_MAC/g' "$MODIFIED_UDEV_NET_SETUP_LINK_DIR"/80-net-setup-link.rules
    update-initramfs -u -t -k "$(uname -r)"
  fi

	;;
esac

exit 0
