#!/bin/bash -eux
#
# Copyright 2024 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

case $1 in
upgrade)
        sed -i 's|/export/home|/home|g' /etc/fstab
        mount /home
        echo $(mount | grep home)

        if [[ -e /etc/auto.master  ]]
          then
            auto_home_line="$(grep auto_home auto)"
            line_len=$(expr length "${auto_home_line}")
            if [[ "$line_len" -gt 0 ]]
              then
                sed -i 's|/home   auto_home    -nobrowse|#/home   auto_home    -nobrowse|g' auto
                systemctl restart autofs
            fi
        fi
        ;;
esac

exit 0
