#!/bin/bash -eux
#
# Copyright 2018 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

case $1 in
    upgrade|remove)
	#
	# Removal is not quite the opposite of installation; we leave the
	# non-delphix services alone, even if the postinst script changed
	# the state of these services. This is because we don't know what
	# the state of these services was before the postinst script ran,
	# so we can't reliably restore the system back to that prior state.
	#

	systemctl disable delphix-platform.service

	;;
esac

exit 0
