#!/bin/bash -eux
#
# Copyright 2018, 2019 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# The units this package ships are disabled by the dh_installsystemd snippet
# in postrm, which runs on removal only. Nothing here may disable them on
# upgrade: dpkg unpacks every package in a transaction before it configures
# any of them, so a disable at unpack leaves the appliance with the delphix
# services off for the whole unpack phase, and permanently if the upgrade is
# interrupted before postinst re-enables them.
#
# Services this package does not ship are left alone on removal, even where
# postinst changed their state, because we don't know what that state was
# beforehand and so can't reliably restore it.
#
case $1 in
upgrade | remove)
	#
	# Remove the "ansible-done" file, to ensure that package removal
	# will remove the "/var/lib/delphix-platform" directory. Since the
	# "ansible-done" file isn't "owned' by the package, if it exists,
	# it'll cause the package manager to leave the file and directory
	# lingering on the filesystem on uninstallation; the package removal
	# will succeed, but the directory won't be removed.
	#
	# Also note, this command needs to stay in sync with the command
	# that's executed when "systemctl reload delphix-platform" is
	# called. See the "delphix-platform.service" file for details.
	#
	rm -f /var/lib/delphix-platform/ansible-done

	;;
esac

#DEBHELPER#

exit 0
