#!/bin/bash -eux
#
# Copyright 2018 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

case $1 in
    upgrade|remove)
	#
	# We need to remove the "ansible-done" file, to ensure that
	# package removal will remove the "/var/lib/delphix-platform"
	# directory. Since the "ansible-done" file isn't "owned' by the
	# package, if it exists, it'll cause the package manager to
	# leave the file and directory lingering on the filesystem on
	# uninstallation; the package removal will succeed, but the
	# directory won't be removed.
	#
	# Also note, this command needs to stay in sync with the command
	# that's executed when "systemctl reload delphix-platform" is
	# called. See the "delphix-platform.service" file for details.
	#
	rm -f /var/lib/delphix-platform/ansible-done

	;;
esac

exit 0
