#
# Configure SSH to allow PAM "conversations" (interactions with the user).
#
ChallengeResponseAuthentication yes
KbdInteractiveAuthentication yes
UsePam yes

#
# Harden the appliance by disabling ssh-agent(1), tcp, UNIX domain, and X11
# forwarding. Note that this doesn't improve security unless users are also
# denied shell access.
#
AllowAgentForwarding no
AllowStreamLocalForwarding no
AllowTcpForwarding no
X11Forwarding no

Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,sntrup761x25519-sha512@openssh.com
MACs umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512
HostKeyAlgorithms -ssh-rsa*

#
# The 'ClientAliveInterval' setting determines the amount of time (in seconds)
# the sshd server will wait to receive data from the client before sending a
# request for response.
#
ClientAliveCountMax 3
ClientAliveInterval 300

LoginGraceTime 60
MaxAuthTries 4
MaxStartups 10:30:60
PermitRootLogin no
PrintLastLog no
