# Disable esp4, esp6, rxrpc modules due to CVE-2026-43500 (dirty frag)
# This will likely be re-enabled in a subsequent update once an updated
# kernel has been deployed.
# Blacklisting the module isn't sufficient, we need to do as below:
install esp4 /bin/false
install esp6 /bin/false
install rxrpc /bin/false